-- CREATE TABLE contractors
-- (
--   id INT NOT NULL AUTO_INCREMENT,
--   name VARCHAR(255) NOT NULL,
--   contact INT NOT NULL,
--   skills VARCHAR(255),
--   address VARCHAR(255),
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE jobs
-- (
--   id INT NOT NULL AUTO_INCREMENT,
--   location VARCHAR(255) NOT NULL,
--   contact VARCHAR(255) NOT NULL,
--   description VARCHAR(255),
--   PRIMARY KEY (id)
-- );
-- DROP TABLE contractors;
-- INSERT INTO contractors (name, contact, skills, address) VALUES ("Bob the Builder", 5551234, "All Trades included", "The Workshop");
-- SELECT * FROM jobs;
-- SELECT * FROM contractors;